name: dam-monitoring
channels: [conda-forge, pytorch, nvidia]
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - pywavelets
  - optuna
  - matplotlib
  - pip
  - pip:
      - ruff
      - black
      - pre-commit
      - pytest
